# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
    paths:
      - 'src/main/resources/*.json'
      
env:
    RCLONE_UPLOAD: true
    GITHUB_UPLOAD: flase

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 签出代码
        uses: actions/checkout@v2
      - name: 初始化GraalVM-17
        uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 21.3.0
          native-image: false
      - name: 开始打包
        run: |
          mvn -B clean package -Dmaven.test.skip=true --file pom.xml -T 4
      - name: 开始下载
        run: |
          cd ./target
          java -jar -Xms1g -Xmx7g ./*.jar
      - name: Install Rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
      - name: Set Rclone
        run: |
          echo "${{ secrets.RCLONE_CONF }}" > rclone.conf
          mkdir -p /home/runner/.config/rclone/
          chmod 777 /home/runner/.config/rclone/
          mv $GITHUB_WORKSPACE/rclone.conf /home/runner/.config/rclone/
      - name: Rclone上传
        if: env.RCLONE_UPLOAD == 'true'
        run: |
          pwd
          df -h
          #mkdir -p /home/runner/work/result
          #tar -cPvf /home/runner/work/result/finder.tar /home/runner/work/finder/
          rclone copy -v --transfers 12 --checkers 16 --onedrive-chunk-size 200M /home/runner/work/finder/ onedrive:/二次元/漫画/18+/禁漫天堂/
          #rclone copy -v --transfers 12 --checkers 16 --onedrive-chunk-size 200M /home/runner/work/result/ onedrive:/二次元/漫画/18+/禁漫天堂/
      - name: 开始上传
        if: env.GITHUB_UPLOAD == 'true'
        uses: actions/upload-artifact@v2.2.2
        with:
          # Artifact name
          name: finder-result
          # A file, directory or wildcard pattern that describes what to upload
          path: /home/runner/work/finder
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: warn
          # Duration after which artifact will expire in days. 0 means using default retention.Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
          retention-days: 90
